// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0uioLvVsv2p8QRKsi2f9fb3q7L1SIq7E',
    appId: '1:890972056628:web:21f206620e20aa6fa16e61',
    messagingSenderId: '890972056628',
    projectId: 'your-fitness-ai-app-d1523',
    authDomain: 'your-fitness-ai-app-d1523.firebaseapp.com',
    storageBucket: 'your-fitness-ai-app-d1523.firebasestorage.app',
    measurementId: 'G-S6QFR8V1ZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHsvWBz7pu0DhgI53T_jomp-Mw8c822FA',
    appId: '1:890972056628:android:71cfd098a76c31c3a16e61',
    messagingSenderId: '890972056628',
    projectId: 'your-fitness-ai-app-d1523',
    storageBucket: 'your-fitness-ai-app-d1523.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGtJ5FfRiSndsC1uZ70zIoldkS73D8dYA',
    appId: '1:890972056628:ios:9e77ea22971121dea16e61',
    messagingSenderId: '890972056628',
    projectId: 'your-fitness-ai-app-d1523',
    storageBucket: 'your-fitness-ai-app-d1523.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGtJ5FfRiSndsC1uZ70zIoldkS73D8dYA',
    appId: '1:890972056628:ios:9e77ea22971121dea16e61',
    messagingSenderId: '890972056628',
    projectId: 'your-fitness-ai-app-d1523',
    storageBucket: 'your-fitness-ai-app-d1523.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0uioLvVsv2p8QRKsi2f9fb3q7L1SIq7E',
    appId: '1:890972056628:web:39ca2ac79e25bdbfa16e61',
    messagingSenderId: '890972056628',
    projectId: 'your-fitness-ai-app-d1523',
    authDomain: 'your-fitness-ai-app-d1523.firebaseapp.com',
    storageBucket: 'your-fitness-ai-app-d1523.firebasestorage.app',
    measurementId: 'G-PJ0XYBX73S',
  );
}
